# -*- coding: utf-8 -*-
"""premier league predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNtedq6_AF2j5HuI5CqVwMdJW8gUpvBb

IMPORT LIBRIRES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import pickle
import streamlit as st
from pyngrok import ngrok

"""LOAD DATA"""

df1 = pd.read_csv("/content/E0.csv")
df2 = pd.read_csv("/content/E0 (4).csv")
df3 = pd.read_csv("/content/E0 (3).csv")
df4 = pd.read_csv("/content/E0 (2).csv")
df5 = pd.read_csv("/content/E0 (1).csv")

all = [df1,df2,df3,df4,df5]
df = pd.concat(all,ignore_index=True)

"""CLEANING DATA"""

df.head()

data = pd.DataFrame(df)

data.info()

data.isna().sum().sort_values(ascending=False)

cols_to_drop = ["1XBA","1XBD","1XBH","BFE>2.5","BFE<2.5"]
data.columns = data.columns.str.strip()
data.drop(columns=[c for c in cols_to_drop if c in data.columns], inplace=True)
data.isna().sum().sort_values(ascending=False)

data.info()

cols_to_drop = ["BFH","BFA","BFD","BFEH","BFED"]
data.columns = data.columns.str.strip()
data.drop(columns=[c for c in cols_to_drop if c in data.columns], inplace=True)
data.isna().sum().sort_values(ascending=False)

cols_to_drop = ["BFEA","BFECD","1XBCH","1XBCD","1XBCA"]
data.columns = data.columns.str.strip()
data.drop(columns=[c for c in cols_to_drop if c in df.columns], inplace=True)
data.isna().sum().sort_values(ascending=False)

cols_to_drop = ["BFECA","BFCH","BFCD","BFEAHA","BFEAHH"]
data.columns = data.columns.str.strip()
data.drop(columns=[c for c in cols_to_drop if c in df.columns], inplace=True)
data.isna().sum().sort_values(ascending=False)

cols_to_drop = ["BFEC>2.5","BFEC<2.5","BFECAHH","BFECAHA","BFCA"]
data.columns = data.columns.str.strip()
data.drop(columns=[c for c in cols_to_drop if c in df.columns], inplace=True)
data.isna().sum().sort_values(ascending=False)

data.drop("BFECH",axis=1,inplace=True)
data.isna().sum().sort_values(ascending=False)

data.info()

list(data.columns)

data = data.loc[:, ~data.columns.str.contains(
    'B365|BW|PS|WH|Max|Avg|>2\\.5|<2\\.5|AH|CH|IW|VC'
)]

data.drop("Div",axis=1,inplace=True)

data.info()

"""MAPPING"""

column_mapping = {
    'Date': 'Date',
    'Time': 'Time',
    'HomeTeam': 'HomeTeam',
    'AwayTeam': 'AwayTeam',
    'FTHG': 'FullTimeHomeGoals',
    'FTAG': 'FullTimeAwayGoals',
    'FTR': 'FullTimeResult',
    'HTHG': 'HalfTimeHomeGoals',
    'HTAG': 'HalfTimeAwayGoals',
    'HTR': 'HalfTimeResult',
    'Referee': 'Referee',
    'HS': 'HomeShots',
    'AS': 'AwayShots',
    'HST': 'HomeShotsOnTarget',
    'AST': 'AwayShotsOnTarget',
    'HF': 'HomeFouls',
    'AF': 'AwayFouls',
    'HC': 'HomeCorners',
    'AC': 'AwayCorners',
    'HY': 'HomeYellowCards',
    'AY': 'AwayYellowCards',
    'HR': 'HomeRedCards',
    'AR': 'AwayRedCards'
}

data.rename(columns=column_mapping, inplace=True)

data.info()

"""analysis & visualization data


"""

data.shape

data["HomeTeam"].unique()

len(df["AwayTeam"].unique())

#الداتا تعبر عن مباريات الدوري الانجليزي اخر خمس مواسم و تحتوي علي ال 27 فريق الذين شاركوا في هذه المواسم

result_counts = data["FullTimeResult"].value_counts()
result_percentage = result_counts / len(data) * 100
print(result_counts)
print(result_percentage)

sns.countplot(data=data,x="FullTimeResult")

# هنا يوضح افضلية الفريق صاحب الارض ففالفوز بنسبة 44 بالمئة

data["TotalGoals"]=data["FullTimeHomeGoals"]+data["FullTimeAwayGoals"]
total_goals = data['TotalGoals'].sum()
avg_goals = data['TotalGoals'].mean()

home_goals = data['FullTimeHomeGoals'].sum()
away_goals = data['FullTimeAwayGoals'].sum()

print(total_goals, avg_goals)
print(home_goals, away_goals)

plt.figure(figsize=(6,4))
sns.histplot(data['TotalGoals'], bins=8, kde=True)
plt.title('Distribution of Goals per Match')
plt.xlabel('Goals per Match')
plt.ylabel('Number of Matches')
plt.show()

# هناتوضيح حجم اللعب الهجومي
#اي ان متوسط عدد الاهداف فالمباراة 3 اهداف

home_wins = data[data['FullTimeResult'] == 'H']["HomeTeam"].value_counts()
away_wins = data[data['FullTimeResult'] == 'A']["AwayTeam"].value_counts()

total_wins = home_wins.add(away_wins, fill_value=0)
wins_df = total_wins.reset_index()
wins_df.columns = ['Team', 'Wins']

top5_wins = wins_df.sort_values(by='Wins', ascending=False).head(5)

plt.figure(figsize=(7,4))
sns.barplot(data=top5_wins, x='Wins', y='Team')
plt.title('Top 5 Teams by Number of Wins (5 Seasons)')
plt.xlabel('Number of Wins')
plt.ylabel('Team')
plt.show()

# man city # اكتر فريق فوز بالمباريات في اخر 5 مواسم

home_points = df.groupby('HomeTeam')['FTR'].apply(
    lambda x: (x == 'H').sum()*3 + (x == 'D').sum()
)

away_points = df.groupby('AwayTeam')['FTR'].apply(
    lambda x: (x == 'A').sum()*3 + (x == 'D').sum()
)

total_points = home_points.add(away_points, fill_value=0)
points_df = total_points.reset_index()
points_df.columns = ['Team', 'Points']

top5_points = points_df.sort_values(by='Points', ascending=False).head(5)

plt.figure(figsize=(7,4))
sns.barplot(data=top5_points, x='Points', y='Team')
plt.title('Top 5 Teams by Points (5 Seasons)')
plt.xlabel('Points')
plt.ylabel('Team')
plt.show()

#man city اكتر فريق جمع نقاط في اخر خمس مواسم

data.isna().sum().sort_values(ascending=False)

data["FullTimeResult"]=data["FullTimeResult"].str.strip()
data["HalfTimeResult"]=data["HalfTimeResult"].str.strip()

ftr_mapping = {'H': 1, 'D': 0, 'A': 2}
data['FullTimeResult'] = data['FullTimeResult'].map(ftr_mapping)

data["FullTimeResult"].unique()

encoder = LabelEncoder()

cat = data.select_dtypes(include='object').columns
for col in cat :
  data[col]=encoder.fit_transform(data[col].astype(str))

data.info()

plt.figure(figsize=(15, 15))
sns.heatmap(data.corr(),annot=True)



"""FAETURE ENGINEERING

"""

data.columns

data["Date"] = pd.to_datetime(data["Date"])
data["Time"] = pd.to_datetime(data["Time"], format="mixed").dt.time

data["Year"] = data["Date"].dt.year
data["Month"] = data["Date"].dt.month
data["Weekday"] = data["Date"].dt.weekday

data["FT_GoalDiff"] = data["FullTimeHomeGoals"] - data["FullTimeAwayGoals"]
data["HT_GoalDiff"] = data["HalfTimeHomeGoals"] - data["HalfTimeAwayGoals"]

data["ShotDiff"] = data["HomeShots"] - data["AwayShots"]
data["ShotOnTargetDiff"] = data["HomeShotsOnTarget"] - data["AwayShotsOnTarget"]

data.info()

#نرتب ع حسب التاريخ عشان نعرف نطلع احصائيات مبنية ع اخر مباريات
data = data.sort_values("Date").reset_index(drop=True)

#فور لووب هتعدي علي كل تيم و تملي الاحصائيات بتاعته
team_states = {}
for team in pd.concat( [data["HomeTeam"],data["AwayTeam"]]).unique() :
  team_states [team] = {
      "goal_scored" : [] , "goals_conceded" : [] , "wins" : [] , "shots" : [] , "shots_on_target" : []
  }

# هننشئ الاعمده الفاضيه اللي هنضيف فيها الاحصائيات دي ف الداتا الاساسية
data["HomeGoals_Last5"] = 0
data["HomeConceded_Last5"] = 0
data["HomeWins_Last5"] = 0
data["HomeShots_Last5"] = 0
data["HomeShotsOnTarget_Last5"] = 0

data["AwayGoals_Last5"] = 0
data["AwayConceded_Last5"] = 0
data["AwayWins_Last5"] = 0
data["AwayShots_Last5"] = 0
data["AwayShotsOnTarget_Last5"] = 0

data.info()

for i, row in data.iterrows():
    home = row["HomeTeam"]
    away = row["AwayTeam"]

    # آخِر 5 ماتشات لكل فريق
    home_last5_goals = team_states[home]["goal_scored"][-5:]
    home_last5_conceded = team_states[home]["goals_conceded"][-5:]
    home_last5_shots = team_states[home]["shots"][-5:]
    home_last5_sot = team_states[home]["shots_on_target"][-5:]
    home_last5_wins = team_states[home]["wins"][-5:]

    away_last5_goals = team_states[away]["goal_scored"][-5:]
    away_last5_conceded = team_states[away]["goals_conceded"][-5:]
    away_last5_shots = team_states[away]["shots"][-5:]
    away_last5_sot = team_states[away]["shots_on_target"][-5:]
    away_last5_wins = team_states[away]["wins"][-5:]

    # نحسب المتوسطات ونضيفها للداتا
    data.loc[i, "HomeGoals_Last5"] = np.mean(home_last5_goals) if len(home_last5_goals) > 0 else 0
    data.loc[i, "HomeConceded_Last5"] = np.mean(home_last5_conceded) if len(home_last5_conceded) > 0 else 0
    data.loc[i, "HomeShots_Last5"] = np.mean(home_last5_shots) if len(home_last5_shots) > 0 else 0
    data.loc[i, "HomeShotsOnTarget_Last5"] = np.mean(home_last5_sot) if len(home_last5_sot) > 0 else 0
    data.loc[i, "HomeWins_Last5"] = np.mean(home_last5_wins) if len(home_last5_wins) > 0 else 0

    data.loc[i, "AwayGoals_Last5"] = np.mean(away_last5_goals) if len(away_last5_goals) > 0 else 0
    data.loc[i, "AwayConceded_Last5"] = np.mean(away_last5_conceded) if len(away_last5_conceded) > 0 else 0
    data.loc[i, "AwayShots_Last5"] = np.mean(away_last5_shots) if len(away_last5_shots) > 0 else 0
    data.loc[i, "AwayShotsOnTarget_Last5"] = np.mean(away_last5_sot) if len(away_last5_sot) > 0 else 0
    data.loc[i, "AwayWins_Last5"] = np.mean(away_last5_wins) if len(away_last5_wins) > 0 else 0

    # بعد كده نحدث القاموس نفسه بالماتش ده
    team_states[home]["goal_scored"].append(row["FullTimeHomeGoals"])
    team_states[home]["goals_conceded"].append(row["FullTimeAwayGoals"])
    team_states[home]["shots"].append(row["HomeShots"])
    team_states[home]["shots_on_target"].append(row["HomeShotsOnTarget"])
    team_states[home]["wins"].append(1 if row["FullTimeResult"]=="H" else 0)

    team_states[away]["goal_scored"].append(row["FullTimeAwayGoals"])
    team_states[away]["goals_conceded"].append(row["FullTimeHomeGoals"])
    team_states[away]["shots"].append(row["AwayShots"])
    team_states[away]["shots_on_target"].append(row["AwayShotsOnTarget"])
    team_states[away]["wins"].append(1 if row["FullTimeResult"]=="A" else 0)

data.head()

data.info()

data.columns

features = [
    'HomeTeam','AwayTeam',
    'HomeGoals_Last5','HomeConceded_Last5','HomeWins_Last5','HomeShots_Last5','HomeShotsOnTarget_Last5',
    'AwayGoals_Last5','AwayConceded_Last5','AwayWins_Last5','AwayShots_Last5','AwayShotsOnTarget_Last5'
]
target = 'FullTimeResult'
X = data[features]
y = data[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestClassifier(random_state=42)

rf_params = {
    'n_estimators': [100, 200,300],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2,5, 10]
}

rf_grid = GridSearchCV(rf, rf_params, cv=3, scoring='accuracy', n_jobs=-1)
rf_grid.fit(X_train, y_train)

print("Best Random Forest Params:", rf_grid.best_params_)
rf_best = rf_grid.best_estimator_

y_pred_rf = rf_best.predict(X_test)
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

xgb = XGBClassifier(use_label_encoder=True, eval_metric='mlogloss', random_state=42)

xgb_params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2,0,5]
}

xgb_grid = GridSearchCV(xgb, xgb_params, cv=3, scoring='accuracy', n_jobs=-1)
xgb_grid.fit(X_train, y_train)

print("Best XGBoost Params:", xgb_grid.best_params_)
xgb_best = xgb_grid.best_estimator_

y_pred_xgb = xgb_best.predict(X_test)
print("XGBoost Accuracy:", accuracy_score(y_test, y_pred_xgb))

with open('rf_grid.pkl', 'wb') as f:
    pickle.dump(rf_grid, f)

import pickle
from sklearn.preprocessing import LabelEncoder

# الأعمدة اللي معمول لها Encoding
cols_to_encode = ['HomeTeam','AwayTeam','Referee']

encoders = {}

for col in cols_to_encode:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

# حفظ Encoders
with open('encoders.pkl', 'wb') as f:
    pickle.dump(encoders, f)

with open('ftr_mapping.pkl','wb') as f :
  pickle.dump(ftr_mapping,f)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# import pandas as pd
# with open('rf_grid.pkl', 'rb') as f:
#     model = pickle.load(f)
# with open('encoders.pkl', 'rb') as f:
#     encoders = pickle.load(f)
# with open('ftr_mapping.pkl', 'rb') as f:
#    ftr_mapping  = pickle.load(f)
# inv_ftr_mapping = {0:'Draw', 1:'Home Win', 2:'Away Win'}
# st.title("Premier League Match Predictor")
# 
# # Dropdown للفرق
# home_team = st.selectbox("Home Team", encoders['HomeTeam'].classes_)
# away_team = st.selectbox("Away Team", encoders['AwayTeam'].classes_)
# 
# st.subheader("Last 5 Matches Stats (Optional)")
# 
# # Home team stats
# home_goals = st.number_input("Home Goals Last 5", min_value=0, value=10)
# home_conceded = st.number_input("Home Conceded Last 5", min_value=0, value=5)
# home_wins = st.number_input("Home Wins Last 5", min_value=0, value=3)
# home_shots = st.number_input("Home Shots Last 5", min_value=0, value=40)
# home_shots_on_target = st.number_input("Home Shots on Target Last 5", min_value=0, value=20)
# 
# # Away team stats
# away_goals = st.number_input("Away Goals Last 5", min_value=0, value=8)
# away_conceded = st.number_input("Away Conceded Last 5", min_value=0, value=7)
# away_wins = st.number_input("Away Wins Last 5", min_value=0, value=2)
# away_shots = st.number_input("Away Shots Last 5", min_value=0, value=35)
# away_shots_on_target = st.number_input("Away Shots on Target Last 5", min_value=0, value=18)
# 
# if st.button("Predict Result"):
#     # Encode الفرق
#     home_enc = encoders['HomeTeam'].transform([home_team])[0]
#     away_enc = encoders['AwayTeam'].transform([away_team])[0]
# 
#     # DataFrame للتنبؤ
#     X_new = pd.DataFrame([[
#         home_enc, away_enc,
#         home_goals, home_conceded, home_wins, home_shots, home_shots_on_target,
#         away_goals, away_conceded, away_wins, away_shots, away_shots_on_target
#     ]], columns=[
#         'HomeTeam','AwayTeam',
#         'HomeGoals_Last5','HomeConceded_Last5','HomeWins_Last5','HomeShots_Last5','HomeShotsOnTarget_Last5',
#         'AwayGoals_Last5','AwayConceded_Last5','AwayWins_Last5','AwayShots_Last5','AwayShotsOnTarget_Last5'
#     ])
# 
#     # Predict
#     pred_num = model.predict(X_new)[0]
#     pred_label = inv_ftr_mapping [pred_num]
# 
#     st.success(f"Predicted Result: {pred_label}")

from pyngrok import ngrok
import os
ngrok.set_auth_token("37576vlCKlR7vOvO9tnQRUPJPCB_4jCK6YWa2vhv9sDwFH16C")
ngrok.kill()
os.system("streamlit run app.py &")
url = ngrok.connect(8501)
print("Streamlit URL:", url)

!pkill streamlit
from pyngrok import ngrok
ngrok.kill()